### PR TITLE
Fix jiggly simulation bug

### PR DESCRIPTION
**Pull request by Lartrax**
The problem:

[1.15.x](https://github.com/u3dreal/molecular-plus/assets/89910638/62958fd7-928e-4465-8403-75feae6a850f)

[1.14.1](https://github.com/u3dreal/molecular-plus/assets/89910638/6658583f-ea30-41e5-9854-37cded214ede)

Don't know why this is happening, so I'll just try some stuff till it works again

### CODE REVIEW

**Comment by Lartrax** [comment]
Reverting rellength did not work, same results

**Comment by u3dreal** [comment]
Hi i will have to go through all this ... give me some time .

**Comment by u3dreal** [comment]
Hi Latrax you mixed up all the changes at once .... it is not possible to get an easy overview .. i totally like your involvement but all that in one commit ... nope Sorry 
Better keep comits small and explain what you have done .. pm me if you have questions

**Comment by u3dreal** [comment]
You also removed all the stuff i left in there for futher ideas ... man .....

**Comment by u3dreal** [comment]
go one change at the time. There is alot of stuff i would like to discuss first. Sorry ...

**Comment by Lartrax** [comment]
Sorry, I was just testing, hence the draft. If i were to make it ready for review i would clean it up. 

Didn't mean to delete your stuff was just reverting to [1.14.1 diff main](https://github.com/u3dreal/molecular-plus/compare/873a118..main) to test if the issue was a code change. I believe I have found it to not be the case.

**Comment by Lartrax** [comment]
TAO seems to have found a solution, so I'm closing my pull request since I could not find a solution.

**Pull request closed without merging**
