### PR TITLE
Blender 3.0 Support

### PR DESCRIPTION
**Pull request by xzeldon**
* Remove ```DRAW_BOX``` from ```bl_options``` since it was removed from the Blender 3.0 Python API
* Update Python version in CI from ```3.9.2``` to ```3.9.7```

### CODE REVIEW

**Comment by u3dreal** [comment]
Nice on what OS are you ?? does not work on OSX for me or maybe ..
Did you test against 3.0 release ??

**Comment by xzeldon** [comment]
@u3dreal OS: Windows 10 Pro for Workstations 21H1, Blender 3.0.0 from Steam, also tested in Blender 2.93 LTS from Steam

> Nice on what OS are you ?? does not work on OSX for me or maybe .. Did you test against 3.0 release ??

**Comment by u3dreal** [comment]
Not sure how we should do it ... maybe a seperate version for 3.0 ( python 3.9.7 )
otherwise it would break 2.9 support ,..will check

**Comment by u3dreal** [comment]
> @u3dreal OS: Windows 10 Pro for Workstations 21H1, Blender 3.0.0 from Steam, also tested in Blender 2.93 LTS from Steam
> 
> > Nice on what OS are you ?? does not work on OSX for me or maybe .. Did you test against 3.0 release ??

Ah OK that is what i thougth it should work with both since it is both python 3.9 ..  will check on mac:_os

**Comment by u3dreal** [comment]
OK all good !! Thanks ... think about becoming an active member !!

**Pull request merged**
