### PR TITLE
Fixed memory leak.

### PR DESCRIPTION
**Pull request by madevgeny**

### CODE REVIEW

**Comment by u3dreal** [comment]
Hi can you be a bit more desciptive of what you did ??
i saw it is not good to reallocate the particles all the time.

**Comment by u3dreal** [comment]
@madevgeny 

plz let me know on what your thoughts are why this is a mem leak ?

**Comment by madevgeny** [comment]
Hi, oh, yes patch looks strange. I'll look at it again.

**Comment by OmidGhotbi** [comment]
i fixed it in the new code i will create a pull request. also, it needs 46% less memory now. the code was already there it needed to be used in the correct order.

**Comment by u3dreal** [comment]
OK

**Pull request closed without merging**
